### ISSUE TITLE
Prometheus endpoint collector multiplies raw values by 1000

### ISSUE THREAD

**Issue by Ziars** [netdata/go.d.plugin#544] opened 2021-01-21 12:49 UTC
Greetings!

I'm trying to use Netdata v1.28.0 for metrics collection from [prometheus endpoints](https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/prometheus). After configuring it for [redis-exporter](https://github.com/oliver006/redis_exporter) I discovered that the values ​​of the most metrics are multiplied by 1000, for example - raw `redis_up` metric:

``` console
$ curl -s "http://localhost:9121/metrics" | grep -P '^redis_up\b'
redis_up 1
```
And the same metric received from Netdata:

``` console
$ curl -s "http://myhost.net:19999/api/v1/allmetrics%3Fformat=prometheus_all_hosts&source=raw" | grep -P 'netdata_prometheus_redis_up\b'
netdata_prometheus_redis_up{chart="prometheus_redis_exporter_local.redis_up",family="redis_up",dimension="redis_up",instance="lxd-redis"} 1000 1609179403020
```

Plugin configuration was close to the default one, i.e.:

``` yaml
autodetection_retry: 300                                                                                                                                                                                     
max_time_series: 2048                                                                                                                                                                                        
priority: 70000                                                                                                                                                                                              
update_every: 10 

jobs:
  - name: redis_exporter_local
    url: 'http://127.0.0.1:9121/metrics'
```

After checking the source code I've found this constant:

- https://github.com/netdata/go.d.plugin/blob/192e776940faac85e8f742bc01e6bb9d1c6d5108/modules/prometheus/collect.go#L10

Which is used for further multiplying the values ​​of each metric type:

- https://github.com/netdata/go.d.plugin/blob/fb90e49e8388f7301c862045ea5d8a229f596caf/modules/prometheus/collect_histogram.go#L36
- https://github.com/netdata/go.d.plugin/blob/fb90e49e8388f7301c862045ea5d8a229f596caf/modules/prometheus/collect_gauge_counter.go#L27
- https://github.com/netdata/go.d.plugin/blob/fb90e49e8388f7301c862045ea5d8a229f596caf/modules/prometheus/collect_summary.go#L35

What is the purpose of this multiplication? Is there a way to disable it somehow? Such multiplication makes it inconvenient to use Netdata as a metric collector from Prometheus exporters (impossible to get raw metrics from them). Thank you in advance!

**Comment by ilyam8** [comment] 2021-01-21 15:05
Hi @Ziars 👋 

Yes, you are right, prometheus endpoint collector multiplies raw values by 1000.

Reason is Netdata current implementation, see [external plugins.d API docs](https://learn.netdata.cloud/docs/agent/collectors/plugins.d#data-collection)

> value
is the collected value, only integer values are collected. If you want to push fractional values, multiply this value by 100 or 1000 and set the DIMENSION divider to 1000.

Prometheus uses floats - we don't want to lose precision and the collector had to use that workaround with multiplying the value and adding the divisor.

---

I believe Netdata should convert values back (using divisor) while exporting.

I checked:

- `/api/v1/allmetrics?format=prometheus`: value/DIVISOR => export result.
- `/api/v1/allmetrics?format=prometheus&source=as-collected`: export value as is.


@vlvkobal i think Netdata should do calc if there is any MULTIPLIER, DIVISOR and export the result with `source=as-collected`. Any ideas why it is not the case?

**Comment by ilyam8** [comment] 2021-01-21 16:15
[Export documentation](https://learn.netdata.cloud/docs/agent/exporting)

> as-collected
sends to external databases the metrics as they are collected, in the units they are collected. So, counters are sent as counters and gauges are sent as gauges, much like all data collectors do. For example, to calculate CPU utilization in this format, you need to know how to convert kernel ticks to percentage.

I tend to think this is a Netdata agent bug.

**Comment by ilyam8** [comment] 2021-01-21 16:34
@n0guest `as-collected` is an alias for `raw` (or vice versa) 😄

**Comment by n0guest** [comment] 2021-01-21 16:38
> @n0guest `as-collected` is an alias for `raw` (or vice versa)

Huh ... Missed it) Nonetheless, are there any hopes to get it fixed in upcoming 1.28.1 or somewhere close to it?

**Comment by ilyam8** [comment] 2021-01-21 16:39
Upcoming release is 1.29.0 which is about to happen. We are discussing this issue internally.

**Comment by n0guest** [comment] 2021-01-21 17:05
> Upcoming release is 1.29.0 which is about to happen. We are discussing this issue internally.

This works too) If we can help with testing of the fixed version - plz, let us know.

**Comment by vlvkobal** [comment] 2021-01-22 17:05
As we discussed today, the problem is that we use the multiplier/divisor for three different purposes at once:
- handling floating-point numbers;
- changing units;
- making dimensions negative to show them under the x-axis.

If we apply any fixes to the as-collected/raw mode, they will be breaking changes.

There is no straightforward and simple solution to the issue. I think we need to discuss this further. Does anybody have any ideas/thoughts?

**Comment by n0guest** [comment] 2021-01-22 18:19
> There is no straightforward and simple solution to the issue. I think we need to discuss this further. Does anybody have any ideas/thoughts?

@vlvkobal, but I hope you all agree, that current behavior could and should be classified as a major bug for Go plugin. Just because in the current state all metrics, which have gone through Netdata as a proxy, are plainly useless. Exported values are distorted, which forces end-user to "reinvent the wheel", like adding "reverse" process. All the scenarios and options, that I could think of are following:

* recording rule on Prometheus level, but it's just a waste of space and computational resources
* customized Grafana dashboard with extra divisor on each query, but it will require extra manual work preparing them and those dashboards won't be compatible with metrics taken straight from an exporter (i.e. not through Netdata)

So, it's the same as you said above - there is no straightforward and simple solution to the issue. Hence, if Netdata provides metrics from OpenMetrics-compatible exporters (i.e. mostly Prometheus-compatible), this data can't be distorted as it is now. Sorry, for not being useful on this. But I think only Netdata core team knows the current internal structure and following limitations to find a viable solution. 

Nonetheless, we really hope, that this problem will be fixed in near future. Because this feature (i.e. Netdata as reverse proxy) fits very well in scenarios, which were many times rejected by Prometheus core developing team. If I'm not mistaken, many people asked many times about reverse proxy for Prometheus exporters and every time someone from Prometheus core team refused to even discuss such solutions. It's worth noting that their point of view has some reasonable and sound arguments. But demand despite their arguments, demand still exists. So, Netdata could be the solution for this demand.

**Comment by ilyam8** [comment] 2021-01-25 10:10
Closing this issue in favor of https://github.com/netdata/netdata/issues/10549

Thx for reporting, guys!

**Closed by ilyam8** 2021-01-25 10:10 UTC
