### ISSUE TITLE
`prometheus`: original labels being wrapped in dimension label

### ISSUE THREAD

**Issue by Ziars** [netdata/go.d.plugin#558] opened 2021-03-04 10:10 UTC
Greetings!

I'm trying to use Netdata v1.29.2 for metrics collection from [prometheus endpoints](https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/prometheus). After configuring it for [node-exporter](https://github.com/prometheus/node_exporter) I discovered that original exporter's labels are being put to `dimension` label after passing through netdata. For example, raw exporter metric:

``` console
# curl -s localhost:9100/metrics | grep -Em1 'exit_status.+worker_01'
node_supervisord_exit_status{group="workers",name="worker_01"} 0
```

And the same metric, requested from netdata:

``` console
# curl -s "localhost:19999/api/v1/allmetrics?format=prometheus_all_hosts&source=raw" | grep -Em1 'exit_status.+worker_01'
netdata_prometheus_node_supervisord_exit_status{chart="prometheus_node_exporter_local.node_supervisord_exit_status",family="node_supervisord",dimension="group=workers,name=worker_01",instance="my-instance"} 0.0000000 1614602897017
```

The issue here is:

```
dimension="group=workers,name=worker_01"
```

If I'm not mistaken, the only way to retrieve original `group` and `name` labels is by using relabel rules like this one (on the Prometheus side):

``` yaml
  - source_labels:
    - dimension
    regex: .*name=([a-z0-9_]+)
    action: replace
    target_label: name
    replacement: ${1}
```

It's quite inconvenient, because of the necessity to either rewrite most of my already working Grafana dashboards (to parse dimension contents), or to invent relabel rules for each exporter. Are there any alternatives like an option to keep original labels from exporter's metrics without wrapping them in `dimension`? Thank you in advance!

**Comment by ilyam8** [comment] 2021-03-09 16:38
Hi @Ziars 

That is an issue, couldn't agree more 😔

The problem is [current netdata data model](https://learn.netdata.cloud/docs/agent/collectors/plugins.d#the-output-of-the-plugin), as you can see there is no metrics, but only charts and dimensions. And a dimension has id and name. That is what we have - no other place to put labels.

So we _collect_ charts and export charts. I completely understand all the problems and they always bothered me.

> If I'm not mistaken, the only way to retrieve original group and name labels is by using relabel rules 

Yes.

> It's quite inconvenient

Yes, i would say it is opposite to being usable 😄

---

Changing data model is hard due to obvious reasons, but, fortunately, there is some light at the end of the tunnel. We plan to extend existing data model and add dimension level labels (chart labels were added in https://github.com/netdata/netdata/pull/10107).

---

Since it is not the issue with go.d.plugin i am going to close it and create a new one in netdata repo.

**Comment by ilyam8** [comment] 2021-03-12 09:27
This one is not closed, because there is no new one 😉

**Comment by ilyam8** [comment] 2021-07-15 17:05
We are discussing changing the data model topic internally. It will fix this issue and a lot of related issues. No estimation for today. Will share any updates when available.

**Comment by duhow** [comment] 2021-11-30 15:32
Hi @ilyam8 , just faced this exact problem today. Do you have any news on this?

**Comment by ilyam8** [comment] 2021-11-30 16:50
@duhow no news, but it is definitely on our radar and (I hope) will be implemented in 2022.

**Closed** 2022-07-06 13:01 UTC
Labels: question
