### ISSUE TITLE
Unit override options for Prometheus Parser

### ISSUE THREAD

**Issue by linuxgemini** [netdata/go.d.plugin#466] opened 2020-10-22 18:36 UTC
While I was testing bird_exporter I have seen the below snippet:

https://github.com/netdata/go.d.plugin/blob/a1c1fa72aba66e0f9dbf7ed9de239b849b47b474/modules/prometheus/charts.go#L33-L37

Because bird_exporter exports data as a normal integer straight from BIRD Routing Daemon, (in my opinion) the data processed shouldn't be re-valued as this makes exporting this to a larger Prometheus instance makes data processing a bit more difficult.

Is it possible to have unit overrides for the Prometheus Parser? I have filed an issue to bird_exporter (https://github.com/czerwonk/bird_exporter/issues/41) for having detailed labels as well.

**Comment by ilyam8** [comment] 2020-10-28 09:48
> as this makes exporting this to a larger Prometheus instance makes data processing a bit more difficult

Why do you need netdata then? Can scrape from prometheus.

---

> Is it possible to have unit overrides for the Prometheus Parser?

I don't really understand what the problem is. Is it `/s` suffix?

We add it for all [`counter`](https://prometheus.io/docs/concepts/metric_types/#counter) type metrics because it is indeed _/per second_ - netdata internally does calculation/interpolation.

To get real values you need `?source=as-collected`. In that case we need to remove `/s` suffix while exporting @vlvkobal.

This is messy in general, we need to pay more attention to exporting part, it is very important imo.

**Comment by ilyam8** [comment] 2020-11-09 11:24
Closing due to no answer.

**Closed by ilyam8** 2020-11-09 11:24 UTC
Labels: area/module, question
