### ISSUE TITLE
Logstash pipelines

### ISSUE THREAD

**Issue by dtakis** [netdata/go.d.plugin#291] opened 2019-11-25 22:29 UTC
While testing netdata, I noticed that under the logstash local option, the logstash pipelines are listed but the data for the pipelines are empty. Is this a bug or behavior related to "/etc/netdata/go.d/logstash.conf"  configuration?

I tried
curl -XGET 'localhost:9600/_node/stats/pipelines?pretty'
and the response provides in, filtered and out information for the events.

Please note that I use logstash 6.5

Thank you in advance

**Comment by ilyam8** [comment] 2019-11-25 22:46
No, it is a bug

https://github.com/netdata/go.d.plugin/blob/d2124f5e939f71eb4fe968fa73833cb406cc01b4/modules/logstash/apiclient.go#L26

Should be `Events`.

**Comment by ilyam8** [comment] 2019-11-25 22:46
Thx for reporting 👍

**Comment by ilyam8** [comment] 2019-11-26 08:39
the fix will be in the next go.d. release next week

**Comment by dtakis** [comment] 2019-11-26 19:52
Thank you for the update.
Happy to help!

**Comment by dtakis** [comment] 2019-12-04 18:43
Is this fix v1.19-Sprint4 included in v1.19.0-37-nightly?

**Comment by ilyam8** [comment] 2019-12-04 18:54
No, merged it today
https://github.com/netdata/netdata/pull/7418

**Comment by dtakis** [comment] 2020-01-06 12:59
Hi @ilyam8 I still do not see any change in v1.19.0-239-nightly. 
The logstash pipelines are flat (no data are shown).
How could I check that the fix has been applied?

**Comment by ilyam8** [comment] 2020-01-06 16:02
Man, you are right, i had to write chart tests, like

https://github.com/netdata/go.d.plugin/blob/b0f60f60811629adb87eccef7ecde132ebc4a8e7/modules/wmi/wmi_test.go#L495-L506

The problem is wrong chart dimensions(no `pipelines_pipeline_N` prefix)

https://github.com/netdata/go.d.plugin/blob/b0f60f60811629adb87eccef7ecde132ebc4a8e7/modules/logstash/charts.go#L155-L181

https://github.com/netdata/go.d.plugin/blob/b0f60f60811629adb87eccef7ecde132ebc4a8e7/modules/logstash/logstash_test.go#L112-L116

**Comment by ilyam8** [comment] 2020-01-06 16:03
@dtakis sorry, will have it fixed soon 😅 😅

**Closed** 2020-01-07 13:11 UTC
Labels: bug

**Comment by ilyam8** [comment] 2020-01-07 13:13
@dtakis it is fixed finally, but still - https://github.com/netdata/go.d.plugin/issues/291#issuecomment-558523011

If you want to test you could build from source.

**Comment by ilyam8** [comment] 2020-01-15 11:23
@dtakis finally fixed in [v0.14.1](https://github.com/netdata/go.d.plugin/releases/tag/v0.14.1)
