### ISSUE TITLE
vsphere go plugin does not include vm name in alldata api call

### ISSUE THREAD

**Issue by scomoletti** [netdata/go.d.plugin#274] opened 2019-09-27 13:52 UTC
Netdata v1.17.1-20 on CentOS 7.6.1810. vsphere plugin shows the vm id# instead of a vm name when calling alldata via api. Graphs do have the vm name at the top of each section of graphs for each vm. Alldata lacks the group details.

Is there a way to include the vm name for each graph instead of only in the header for each group? This would make both graphs and alldata easier to consume. I know I can override the name attribute in netdata.conf after discovery but when you have hundreds of vm's this isnt realistic.

**Comment by ilyam8** [comment] 2019-09-27 15:25
Hey @scomoletti 

> alldata via api

Do you mean `allmetrics?format=prometheus` ?

Could you post vmsphere metrics there?

it should be something like

> netdata_vsphere_net_packets_total_packets{dimension="vm-id_net.packetsRx.summation", family="vm vm-name(host-name)"}


I want to understand where should i add `vm-name`.

**Comment by scomoletti** [comment] 2019-09-27 17:23
sorry was using allmetrics?format=json. not sure where alldata came from..brain cramp, long week.

In netdata.conf family = guestname + hostname which is fine but family isnt exposed in the json output. It's the name attribute itself which is a combination of the plugin name + vc name+ vm-id + context? (without the vsphere. prefix). 
For example: 
family = vm myguest.mydomain.com (myhost-3-3.mydomain.com)
name = vsphere_vc01.mydomaincom.vm_718_cpu_usage_total

The vm-id makes sense from a code perspective but not a user display perspective since most people never see or know the vm-id, esp if I have a support team responding to alarms from this. They will be looking at the vcenter web console for triage tasks resulting from those alarms.

Is it possible to trim the name attribute to be the plugin + vm name + context? so the above example would become: name = vsphere_myguest.mydomain.com_cpu_usage_total
Or is name used for other purposes which would break if we change that format? 

Sample output from my allmetrics?format=json
	"vsphere_vc01.mydomain.com.vm-718_cpu_usage_total": {
		"name":"vsphere_vc01.mydomain.com.vm_718_cpu_usage_total",
		"context":"vsphere.cpu_usage_total",
		"units":"percentage",
		"last_updated": 1569550720,
		"dimensions": {
			"vm-718_cpu.usage.average": {
				"name": "used",
				"value": 7.7200000
			}
		}
	},

Note that there is no reference to the vm name at all and family isnt included either in allmetrics?format=json.

And the corresponding netdata.conf entry for it:
[vsphere_vc01.mydomain.com.vm-718_cpu_usage_total]
        # history = 3996
        # enabled = yes
        # cache directory = /opt/netdata/var/cache/netdata/vsphere_vc01.mydomain.com.vm_718_cpu_usage_total
        # chart type = area
        # type = vsphere_vc01
        # family = vm myguest.mydomain.com (myhost-3-3.mydomain.com)
        # units = percentage
        # context = vsphere.cpu_usage_total
        # priority = 70200
        # name = vsphere_vc01.mydomain.com.vm_718_cpu_usage_total
        # title = Cpu Usage Total
        # dim vm-718_cpu.usage.average name = used
        # dim vm-718_cpu.usage.average algorithm = absolute
        # dim vm-718_cpu.usage.average multiplier = 1
        # dim vm-718_cpu.usage.average divisor = 100

**Comment by ilyam8** [comment] 2019-09-27 19:33
> In netdata.conf family = guestname + hostname which is fine but family isnt exposed in the json output.

Yes, there is no `family` indeed.

https://github.com/netdata/netdata/blob/2f6f8155dba6951256f5f8e080aafca6e6836dfc/web/api/exporters/shell/allmetrics_shell.c#L94-L120

I think we could add it.

___

I didnt add vm-name to the `chartID` because name is not static, you can rename vm - if i will add to the `chartID` i will have to delete all old charts and create new on rename.


To be honest the problem is lack of labels (we are working on it!), apart from vm-name we need to add cluster name, datacenter name, etc.

**Comment by scomoletti** [comment] 2019-09-27 20:34
I can see the benefit of having DC/Cluster/etc but technically the vsphere plugin isnt tracking metrics on those directly. They are more 'meta data' supporting any potential alarms from the vm or host metrics being tracked. But with the vm name itself an operator can find the rest. I guess technically they can with the vm-id too but I know I'd look at my noc guys funny if they said vm 57 has a memory problem vs giving me a guest name.

That said making a distinction between the chart name (more of an ID...) and a display name would probably go a long way and may be useful for all charts from other collectors aside from this one.

**Comment by ilyam8** [comment] 2019-09-27 20:39
I added `family` to `allmetrics?format=json` in https://github.com/netdata/netdata/pull/6966

Will this work for you?

I understand your point but i would prefer to not encode vm/host name directly into `chartID`. I want to wait labels. We are not that far from it.

**Comment by scomoletti** [comment] 2019-09-27 22:55
sounds good, thanks for the quick response on this!

**Comment by ilyam8** [comment] 2019-09-27 22:57
@scomoletti the PR is merged, please update netdata to the latest

**Closed by ilyam8** 2019-09-27 22:57 UTC
